<a href="https://colab.research.google.com/github/shivammehta007/NLPResearch/blob/master/Tutorials/PyTorch_Tutorial/DeepNNTutorialCoursera/Week3.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [5]:
import torch
import matplotlib.pyplot as plt
import torch.nn as nn
import torch.utils.data as data
%matplotlib inline
torch.manual_seed(1)

# Multiple Linear Regression

In [0]:
model = nn.Linear(in_features=2, out_features=1)

In [7]:
list(model.parameters())

[Parameter containing:
 tensor([[ 0.3643, -0.3121]], requires_grad=True), Parameter containing:
 tensor([-0.1371], requires_grad=True)]

In [0]:
X = torch.tensor([[1.0, 2.0], [1.0, 3.0], [1.0, 4.0]], requires_grad=True)

In [0]:
yHat = model(X)

In [10]:
yHat

tensor([[-0.3969],
        [-0.7090],
        [-1.0211]], grad_fn=<AddmmBackward>)