Link: https://pytorch.org/tutorials/beginner/deep_learning_60min_blitz.html

In [1]:
from __future__ import print_function
import torch

Initializing a matrix

In [56]:
x = torch.empty(6,4)
print(x)
print(x.reshape(4,6))
print(x.view(24))
print(type(x))

tensor([[0.0000e+00, 0.0000e+00, 0.0000e+00, 0.0000e+00],
        [0.0000e+00, 0.0000e+00, 0.0000e+00, 0.0000e+00],
        [0.0000e+00, 0.0000e+00, 0.0000e+00, 0.0000e+00],
        [0.0000e+00, 0.0000e+00, 0.0000e+00, 0.0000e+00],
        [0.0000e+00, 0.0000e+00, 1.5134e-43, 1.4153e-43],
        [0.0000e+00, 1.5846e+29, 0.0000e+00, 1.5846e+29]])
tensor([[0.0000e+00, 0.0000e+00, 0.0000e+00, 0.0000e+00, 0.0000e+00, 0.0000e+00],
        [0.0000e+00, 0.0000e+00, 0.0000e+00, 0.0000e+00, 0.0000e+00, 0.0000e+00],
        [0.0000e+00, 0.0000e+00, 0.0000e+00, 0.0000e+00, 0.0000e+00, 0.0000e+00],
        [1.5134e-43, 1.4153e-43, 0.0000e+00, 1.5846e+29, 0.0000e+00, 1.5846e+29]])
tensor([0.0000e+00, 0.0000e+00, 0.0000e+00, 0.0000e+00, 0.0000e+00, 0.0000e+00,
        0.0000e+00, 0.0000e+00, 0.0000e+00, 0.0000e+00, 0.0000e+00, 0.0000e+00,
        0.0000e+00, 0.0000e+00, 0.0000e+00, 0.0000e+00, 0.0000e+00, 0.0000e+00,
        1.5134e-43, 1.4153e-43, 0.0000e+00, 1.5846e+29, 0.0000e+00, 1.5846e+29])
<

In [24]:
x = torch.rand(5,3)
print(x)
y = torch.zeros(5,3, dtype=torch.float)
print(y)
print(x.size())

tensor([[0.2489, 0.7271, 0.8353],
        [0.1500, 0.1820, 0.8936],
        [0.1194, 0.0495, 0.9269],
        [0.4959, 0.3617, 0.2292],
        [0.3794, 0.3315, 0.9821]])
tensor([[0., 0., 0.],
        [0., 0., 0.],
        [0., 0., 0.],
        [0., 0., 0.],
        [0., 0., 0.]])
torch.Size([5, 3])


In [25]:
b = torch.rand_like(y, dtype=torch.float)
print(b)

tensor([[0.8192, 0.3413, 0.3647],
        [0.4975, 0.4980, 0.2460],
        [0.3414, 0.1600, 0.1107],
        [0.9450, 0.3221, 0.1445],
        [0.4781, 0.0522, 0.2691]])


In [27]:
data = x+y
print(data)

tensor([[0.2489, 0.7271, 0.8353],
        [0.1500, 0.1820, 0.8936],
        [0.1194, 0.0495, 0.9269],
        [0.4959, 0.3617, 0.2292],
        [0.3794, 0.3315, 0.9821]])


In [53]:
c = torch.rand(3,2)
print(c.t())
print(c)
# print(torch.transpose(c, -1,0))

tensor([[0.7790, 0.9756, 0.4448],
        [0.4150, 0.3998, 0.6466]])
tensor([[0.7790, 0.4150],
        [0.9756, 0.3998],
        [0.4448, 0.6466]])


In [44]:
# False Because Macbook -_-
torch.cuda.is_available()

False

## Automatic Gradient : autograd

In [59]:
x = torch.ones(2,2, requires_grad=True)
print(x)

tensor([[1., 1.],
        [1., 1.]], requires_grad=True)


In [60]:
y = x + 2
print(y)

tensor([[3., 3.],
        [3., 3.]], grad_fn=<AddBackward0>)


In [62]:
z = y*y *3
out = z.mean()
print(z)
print(out)

tensor([[27., 27.],
        [27., 27.]], grad_fn=<MulBackward0>)
tensor(27., grad_fn=<MeanBackward0>)


In [64]:
out.backward()

In [65]:
print(x.grad)

tensor([[4.5000, 4.5000],
        [4.5000, 4.5000]])


In [71]:
a = torch.randn(2, 2)
a = ((a * 3) / (a - 1))
print(a.requires_grad)
a.requires_grad_(True)
print(a.requires_grad)
b = (a * a).sum()
print(b.grad_fn)

False
True


In [72]:
b.backward()
print(a.grad)

tensor([[-6.3669,  3.2935],
        [ 3.7578, -1.5249]])


In [84]:
x = torch.rand(3, requires_grad=True)
y = x*2
while y.data.norm() < 1000:
    y = y*2

print(y)

tensor([1101.5992,  625.3781,  273.0513], grad_fn=<MulBackward0>)


In [85]:
v = torch.tensor([0.1, 1.0, 0.0001], dtype=torch.float)
y.backward(v)
print(x.grad)

tensor([2.0480e+02, 2.0480e+03, 2.0480e-01])


In [88]:
with torch.no_grad():
    print( (x**2).requires_grad)
print( (x**2).requires_grad)

False
True
