Link: https://pytorch.org/tutorials/beginner/deep_learning_60min_blitz.html

In [1]:
from __future__ import print_function
import torch

Initializing a matrix

In [2]:
x = torch.empty(6,4)
print(x)
print(x.reshape(4,6))
print(x.view(24))
print(type(x))

tensor([[1.0761e-22, 1.4013e-45, 1.4235e-30, 1.4013e-45],
        [1.2910e-35, 1.4013e-45, 1.4215e-30, 1.4013e-45],
        [1.2761e-22, 1.4013e-45, 1.0739e-22, 1.4013e-45],
        [1.4225e-30, 1.4013e-45, 1.2903e-35, 1.4013e-45],
        [1.4225e-30, 1.4013e-45, 1.2807e-22, 1.4013e-45],
        [1.4215e-30, 1.4013e-45, 1.4215e-30, 1.4013e-45]])
tensor([[1.0761e-22, 1.4013e-45, 1.4235e-30, 1.4013e-45, 1.2910e-35, 1.4013e-45],
        [1.4215e-30, 1.4013e-45, 1.2761e-22, 1.4013e-45, 1.0739e-22, 1.4013e-45],
        [1.4225e-30, 1.4013e-45, 1.2903e-35, 1.4013e-45, 1.4225e-30, 1.4013e-45],
        [1.2807e-22, 1.4013e-45, 1.4215e-30, 1.4013e-45, 1.4215e-30, 1.4013e-45]])
tensor([1.0761e-22, 1.4013e-45, 1.4235e-30, 1.4013e-45, 1.2910e-35, 1.4013e-45,
        1.4215e-30, 1.4013e-45, 1.2761e-22, 1.4013e-45, 1.0739e-22, 1.4013e-45,
        1.4225e-30, 1.4013e-45, 1.2903e-35, 1.4013e-45, 1.4225e-30, 1.4013e-45,
        1.2807e-22, 1.4013e-45, 1.4215e-30, 1.4013e-45, 1.4215e-30, 1.4013e-45])
<

In [3]:
x = torch.rand(5,3)
print(x)
y = torch.zeros(5,3, dtype=torch.float)
print(y)
print(x.size())

tensor([[0.4211, 0.9934, 0.3699],
        [0.6998, 0.4500, 0.8729],
        [0.3409, 0.2364, 0.5567],
        [0.1558, 0.8091, 0.1216],
        [0.2371, 0.9374, 0.0206]])
tensor([[0., 0., 0.],
        [0., 0., 0.],
        [0., 0., 0.],
        [0., 0., 0.],
        [0., 0., 0.]])
torch.Size([5, 3])


In [4]:
b = torch.rand_like(y, dtype=torch.float)
print(b)

tensor([[0.5245, 0.8692, 0.0201],
        [0.8460, 0.9743, 0.0176],
        [0.5257, 0.0147, 0.3019],
        [0.3490, 0.8909, 0.0862],
        [0.5972, 0.9460, 0.9397]])


In [5]:
data = x+y
print(data)

tensor([[0.4211, 0.9934, 0.3699],
        [0.6998, 0.4500, 0.8729],
        [0.3409, 0.2364, 0.5567],
        [0.1558, 0.8091, 0.1216],
        [0.2371, 0.9374, 0.0206]])


In [6]:
c = torch.rand(3,2)
print(c.t())
print(c)
# print(torch.transpose(c, -1,0))

tensor([[0.4724, 0.4628, 0.5393],
        [0.6220, 0.9108, 0.1871]])
tensor([[0.4724, 0.6220],
        [0.4628, 0.9108],
        [0.5393, 0.1871]])


In [7]:
# False Because Macbook -_-
torch.cuda.is_available()

False

## Automatic Gradient : autograd

In [8]:
x = torch.ones(2,2, requires_grad=True)
print(x)

tensor([[1., 1.],
        [1., 1.]], requires_grad=True)


In [9]:
y = x + 2
print(y)

tensor([[3., 3.],
        [3., 3.]], grad_fn=<AddBackward0>)


In [10]:
z = y*y *3
out = z.mean()
print(z)
print(out)

tensor([[27., 27.],
        [27., 27.]], grad_fn=<MulBackward0>)
tensor(27., grad_fn=<MeanBackward0>)


In [11]:
out.backward()

In [12]:
print(x.grad)

tensor([[4.5000, 4.5000],
        [4.5000, 4.5000]])


In [13]:
a = torch.randn(2, 2)
a = ((a * 3) / (a - 1))
print(a.requires_grad)
a.requires_grad_(True)
print(a.requires_grad)
b = (a * a).sum()
print(b.grad_fn)

False
True


In [14]:
b.backward()
print(a.grad)

tensor([[-11.1287,  -1.2985],
        [ -4.6900,  79.2172]])


In [15]:
x = torch.rand(3, requires_grad=True)
y = x*2
while y.data.norm() < 1000:
    y = y*2

print(y)

tensor([   4.8059,  928.2822, 1009.1189], grad_fn=<MulBackward0>)


In [16]:
v = torch.tensor([0.1, 1.0, 0.0001], dtype=torch.float)
y.backward(v)
print(x.grad)

tensor([4.0960e+02, 4.0960e+03, 4.0960e-01])


In [17]:
with torch.no_grad():
    print( (x**2).requires_grad)
print( (x**2).requires_grad)

False
True


In [25]:
x = torch.rand(5, 10, requires_grad=True)

In [37]:
x.view(-1)

tensor([0.2787, 0.5092, 0.6330, 0.0853, 0.1845, 0.6749, 0.2134, 0.4823, 0.3860,
        0.7606, 0.6958, 0.8749, 0.7311, 0.4366, 0.3527, 0.6562, 0.2712, 0.9325,
        0.1516, 0.0092, 0.4119, 0.1704, 0.5580, 0.2106, 0.0903, 0.3065, 0.3325,
        0.3495, 0.2903, 0.4991, 0.3995, 0.6567, 0.8301, 0.3108, 0.5299, 0.8983,
        0.3753, 0.7403, 0.6513, 0.8189, 0.6782, 0.2254, 0.0702, 0.6598, 0.7375,
        0.4342, 0.7455, 0.4047, 0.4849, 0.6905], grad_fn=<ViewBackward>)