# Basics of Numpy

## Array Attributes

In [1]:
import numpy as np


In [5]:
np.random.seed(0)
x1 = np.random.randint(10, size=6)
x2 = np.random.randint(10, size=(3,4))
x3 = np.random.randint(10, size=(3,4,5))

In [13]:
print(x1, x2, x3)
print('Dimension: ',x3.ndim)
print('Shape: ', x3.shape)
print('Size: ', x3.size)
print('DataType: ', x3.dtype)
print('ItemSize: ', x3.itemsize)
print('nBytes: ', x3.nbytes)

[5 0 3 3 7 9] [[3 5 2 4]
 [7 6 8 8]
 [1 6 7 7]] [[[8 1 5 9 8]
  [9 4 3 0 3]
  [5 0 2 3 8]
  [1 3 3 3 7]]

 [[0 1 9 9 0]
  [4 7 3 2 7]
  [2 0 0 4 5]
  [5 6 8 4 1]]

 [[4 9 8 1 1]
  [7 9 9 3 6]
  [7 2 0 3 5]
  [9 4 4 6 4]]]
Dimension:  3
Shape:  (3, 4, 5)
Size:  60
DataType:  int64
ItemSize:  8
nBytes:  480


### Unlike Python List Numpy arrays are type specific